(() => {
  const $ = (id) => document.getElementById(id);
  const canvas = $("game"), ctx = canvas.getContext("2d");
  const locale = navigator.language.toLowerCase().startsWith("tr") ? "tr" : "en";
  document.documentElement.lang = locale;
  const screens = [$("home"), $("levels"), $("settings")];
  if(locale === "en") { $("play-button").textContent="PLAY"; $("levels-button").textContent="LEVELS"; $("settings-button").textContent="SETTINGS"; document.querySelector(".hud-bottom p").textContent="Drag: aim · Tap: fire"; }
  const hud = $("hud"), result = $("result");
  const saved = JSON.parse(localStorage.getItem("orbitEscape") || "{}");
  const store = { highest: saved.highest || 1, stars: saved.stars || {}, coins: saved.coins || 0, sound: saved.sound ?? true, haptics: saved.haptics ?? true, motion: saved.motion ?? matchMedia("(prefers-reduced-motion: reduce)").matches };
  const state = { mode:"home", level:1, escaped:0, lives:3, required:3, outer:0, inner:0, arrows:[], projectile:null, particles:[], last:0, elapsed:0, paused:false, shake:0, ending:false, combo:0, score:0, fever:0, turboReady:false };
  const TAU = Math.PI * 2, launchAngle = -Math.PI / 2;
  let audio;
  let aimTouch = null;

  function save(){localStorage.setItem("orbitEscape",JSON.stringify(store));}
  function levelData(n){ const band=Math.floor((n-1)/10), local=(n-1)%10, count=n<21?4:n<41?5:6, width=Math.max(.16,.54-band*.060-local*.017); return {n,required:Math.min(14,3+Math.floor(n/4)),starts:Math.min(7,Math.max(0,Math.floor((n-4)/7))),outer:(.42+band*.25+local*.045)*(n%2? -1:1),inner:.85*(n%3?1:-1),lives:n>=51?1:n>=26?2:3,gates:Array.from({length:count},(_,i)=>({angle:launchAngle+i*TAU/count+.16,width}))}; }
  function norm(a){return ((a%TAU)+TAU)%TAU} function distance(a,b){return Math.abs(Math.atan2(Math.sin(a-b),Math.cos(a-b)))}
  function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);}
  addEventListener("resize",resize); resize();
  function hideAll(){screens.forEach(s=>s.classList.add("hidden"));hud.classList.add("hidden");result.classList.add("hidden");}
  function home(){state.mode="home";hideAll();$("home").classList.remove("hidden");$("last-level").textContent=`Bölüm ${store.highest} · ${store.coins} Yörünge Pulu`;}
  function levels(){state.mode="levels";hideAll();$("levels").classList.remove("hidden");renderLevels();}
  function settings(){state.mode="settings";hideAll();$("settings").classList.remove("hidden");$("sound-toggle").checked=store.sound;$("haptics-toggle").checked=store.haptics;$("motion-toggle").checked=store.motion;}
  function renderLevels(){const grid=$("level-grid");grid.innerHTML="";for(let n=1;n<=60;n++){const b=document.createElement("button"),open=n<=store.highest;b.className="level"+(open?"":" locked");b.disabled=!open;b.innerHTML=`<span>${n}</span><small>${"★".repeat(store.stars[n]||0)}</small>`;b.setAttribute("aria-label",open?`Bölüm ${n}`:`Bölüm ${n}, kilitli`);b.onclick=()=>start(n);grid.appendChild(b)}}
  function start(n){const l=levelData(n);Object.assign(state,{mode:"game",level:n,escaped:0,lives:l.lives,required:l.required,outer:0,inner:0,projectile:null,particles:[],elapsed:0,paused:false,shake:0,ending:false,combo:0,score:0,fever:0});state.arrows=Array.from({length:l.starts},(_,i)=>launchAngle+(i+1)*TAU/(l.starts+1));hideAll();hud.classList.remove("hidden");updateHUD();}
  function updateHUD(){$("level-label").textContent=`BÖLÜM ${state.level}`;$("escape-label").textContent=`KAÇIŞ ${state.escaped} / ${state.required}`;$("combo-label").textContent=state.turboReady?`TURBO HAZIR · ${state.score} PUAN`:state.fever>0?`YILDIZ AKIŞI · ${state.score} PUAN`:`AKIŞ x${state.combo} · ${state.score} PUAN`;$("lives").innerHTML=Array.from({length:levelData(state.level).lives},(_,i)=>`<i class="life ${i<state.lives?"":"empty"}"></i>`).join("")}
  function tone(freq,duration,type="sine"){if(!store.sound)return;audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
  function vibrate(pattern){if(store.haptics&&navigator.vibrate)navigator.vibrate(pattern)}
  function turboAngle(){return launchAngle+state.elapsed*1.7+Math.sin(state.elapsed*1.1)*.28}
  function fire(){if(state.mode!=="game"||state.paused||state.projectile||state.ending)return;const angle=launchAngle+state.inner,boost=distance(angle,turboAngle())<.24;tone(boost?510:340,.06,"square");state.projectile={r:15,angle,checkedInner:false,boost};}
  function burst(x,y,color,count){for(let i=0;i<count;i++){const a=Math.random()*TAU,s=55+Math.random()*170;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.35,color,size:2+Math.random()*4})}}
  function resolve(success,x,y,perfect=false,boost=false){if(success){state.escaped++;state.combo++;state.score+=100*state.combo+(perfect?180:0)+(boost?260:0);if(boost){state.fever=Math.max(state.fever,2.4);burst(x,y,"#3debff",store.motion?46:14);tone(960,.2,"triangle");vibrate([10,16,10])}else if(state.combo>=3&&state.fever<=0){state.fever=3.4;burst(x,y,"#3debff",store.motion?42:12);tone(880,.22,"triangle");vibrate([12,20,12])}else{burst(x,y,perfect?"#3debff":"#a7f84b",store.motion?(perfect?30:18):7);tone(perfect?780:660,.12,"sine");vibrate(10)}if(state.escaped>=state.required){finish(true)}else updateHUD()}else{state.lives--;state.combo=0;state.fever=0;state.shake=store.motion?.22:0;burst(x,y,"#ff5d7a",store.motion?26:9);tone(120,.17,"sawtooth");vibrate([20,25,35]);updateHUD();if(state.lives<=0)finish(false)}state.projectile=null;}
  function finish(win){if(state.ending)return;state.ending=true;setTimeout(()=>{const l=levelData(state.level);let stars=win?(state.lives===l.lives?(state.elapsed<=Math.max(10,25-Math.floor((state.level-1)/10)*2)?3:2):1):0,earned=0;if(win){earned=12+stars*8+Math.floor(state.score/100);store.coins+=earned;store.highest=Math.min(60,Math.max(store.highest,state.level+1));store.stars[state.level]=Math.max(store.stars[state.level]||0,stars);save()}$("result-symbol").className="result-symbol "+(win?"win":"loss");$("result-title").textContent=win?"YÖRÜNGE TAMAMLANDI":"YÖRÜNGE KIRILDI";$("result-copy").textContent=win?`+${earned} Yörünge Pulu · Toplam: ${store.coins}`:"Ok, iç halkadaki oka veya kapalı bölgeye çarptı.";$("result-stars").textContent=win?"★".repeat(stars):"";$("result-primary").textContent=win?(state.level<60?"SONRAKİ BÖLÜM":"BÖLÜMLERE DÖN"):"TEKRAR DENE";$("result-primary").onclick=()=>win?(state.level<60?start(state.level+1):levels()):start(state.level);result.classList.remove("hidden");},win?250:80)}
  function radius(){const r=canvas.getBoundingClientRect();return Math.min(r.width,r.height)*.19} function outerRadius(){return radius()*1.77}
  function pt(a,r){return {x:canvas.clientWidth/2+Math.cos(a)*r,y:canvas.clientHeight/2+Math.sin(a)*r}}
  function activeGates(l){const phase=Math.floor((state.level-1)/10);return l.gates.map((g,index)=>{let angle=g.angle,width=g.width;if(phase>=1)width*=.88+.12*(.5+.5*Math.sin(state.elapsed*2.3+index));if(phase>=2)angle+=Math.sin(state.elapsed*1.45+index*1.7)*.14;if(phase>=4)angle+=Math.sin(state.elapsed*3.1+index)*.06;return {angle,width}})}
  function update(dt){if(state.mode!=="game"||state.paused||state.ending)return;const l=levelData(state.level),phase=Math.floor((state.level-1)/10);state.elapsed+=dt;state.fever=Math.max(0,state.fever-dt);const flip=phase>=3&&Math.floor(state.elapsed/3.8)%2?-.72:1;state.inner+=l.inner*dt;state.outer+=l.outer*flip*(state.fever>0?.62:1)*dt;state.turboReady=distance(launchAngle+state.inner,turboAngle())<.24;if(state.projectile){const p=state.projectile;p.r+=Math.min(dt,.033)*920;const coreR=radius(),outerR=outerRadius();if(!p.checkedInner&&p.r>=coreR){p.checkedInner=true;const local=norm(p.angle-state.inner);if(state.arrows.some(a=>distance(a,local)<.12)){const q=pt(p.angle,p.r);resolve(false,q.x,q.y);return}}if(p.r>=outerR){const local=norm(p.angle-state.outer),gates=activeGates(l),hit=gates.find(g=>distance(g.angle,local)<g.width/2),perfect=hit&&distance(hit.angle,local)<hit.width*.20,q=pt(p.angle,p.r);resolve(Boolean(hit),q.x,q.y,Boolean(perfect),p.boost);}}for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);state.shake=Math.max(0,state.shake-dt);updateHUD()}
  function arc(a,r,start,end,color,width,glow=0,cap="round"){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap=cap;if(glow){ctx.shadowBlur=glow;ctx.shadowColor=color}ctx.beginPath();ctx.arc(0,0,r,start+a,end+a);ctx.stroke();ctx.restore()}
  function outerRingWithGaps(r,gates){
    const gaps=[];
    for(const gate of gates){
      const start=norm(gate.angle+state.outer-gate.width/2),end=norm(gate.angle+state.outer+gate.width/2);
      if(start>end){gaps.push({start,end:TAU},{start:0,end})}else gaps.push({start,end});
    }
    gaps.sort((a,b)=>a.start-b.start);
    let cursor=0;
    for(const gap of gaps){
      if(gap.start>cursor) arc(0,r,cursor,gap.start,"#b6bde655",11,0,"butt");
      cursor=Math.max(cursor,gap.end);
    }
    if(cursor<TAU) arc(0,r,cursor,TAU,"#b6bde655",11,0,"butt");
    for(const gate of gates){
      const start=gate.angle+state.outer-gate.width/2,end=gate.angle+state.outer+gate.width/2;
      arc(0,r,start-.055,start+.025,"#d9795c",5,5);
      arc(0,r,end-.025,end+.055,"#d9795c",5,5);
    }
  }
  function drawArrow(angle,r,color="#3debff",length=34){ctx.save();ctx.rotate(angle+Math.PI/2);ctx.translate(0,-r);ctx.fillStyle=color;ctx.shadowBlur=12;ctx.shadowColor=color;ctx.fillRect(-2,-27,4,30);ctx.beginPath();ctx.moveTo(0,-38);ctx.lineTo(-8,-23);ctx.lineTo(8,-23);ctx.closePath();ctx.fill();ctx.restore()}
  function draw(){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);if(state.mode!=="game")return;const cx=canvas.clientWidth/2,cy=canvas.clientHeight/2,coreR=radius(),outerR=outerRadius(),l=levelData(state.level),turbo=turboAngle();ctx.save();if(state.shake){const x=(Math.random()-.5)*state.shake*26;ctx.translate(x,0)}ctx.translate(cx,cy);if(state.fever>0){ctx.fillStyle="#3debff10";ctx.beginPath();ctx.arc(0,0,outerR+32,0,TAU);ctx.fill();arc(0,outerR+26,0,TAU,"#3debff",2,12)}ctx.fillStyle="#131a3acc";ctx.beginPath();ctx.arc(0,0,coreR,0,TAU);ctx.fill();arc(0,coreR,0,TAU,"#8b5cff",6,16);arc(0,coreR+14,0,TAU,"#8b5cff33",13);ctx.save();ctx.rotate(-state.elapsed*.75);for(let i=0;i<3;i++)arc(0,coreR*.40,i*TAU/3+.10,i*TAU/3+.70,"#8b5cff66",4,6);ctx.restore();arc(0,coreR*.62,turbo-.20,turbo+.20,"#a7f84b",5,12);const turboPoint={x:Math.cos(turbo)*coreR*.62,y:Math.sin(turbo)*coreR*.62};ctx.fillStyle="#a7f84b";ctx.shadowBlur=16;ctx.shadowColor="#a7f84b";ctx.beginPath();ctx.arc(turboPoint.x,turboPoint.y,state.turboReady?8:5,0,TAU);ctx.fill();ctx.shadowBlur=0;outerRingWithGaps(outerR,activeGates(l));ctx.save();ctx.rotate(state.inner);state.arrows.forEach(a=>drawArrow(a,coreR));drawArrow(launchAngle,coreR*.52,state.turboReady?"#a7f84b":"#3debff");ctx.restore();if(state.projectile)drawArrow(state.projectile.angle,state.projectile.r,state.projectile.boost?"#a7f84b":"#3debff");ctx.restore();for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,TAU);ctx.fill()}ctx.globalAlpha=1;}
  function tick(t){const dt=Math.min(.04,(t-state.last)/1000||0);state.last=t;update(dt);draw();requestAnimationFrame(tick)}requestAnimationFrame(tick);
  $("play-button").onclick=()=>start(store.highest);$("levels-button").onclick=levels;$("settings-button").onclick=settings;document.querySelectorAll(".back-home").forEach(b=>b.onclick=home);$("quit-button").onclick=levels;$("pause-button").onclick=()=>{state.paused=!state.paused;$("pause-button").textContent=state.paused?"▶":"Ⅱ"};$("result-exit").onclick=levels;$("sound-toggle").onchange=e=>{store.sound=e.target.checked;save()};$("haptics-toggle").onchange=e=>{store.haptics=e.target.checked;save()};$("motion-toggle").onchange=e=>{store.motion=e.target.checked;save()};canvas.addEventListener("pointerdown",e=>{if(state.mode!=="game"||state.paused)return;aimTouch={x:e.clientX,inner:state.inner,moved:false};canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!aimTouch)return;const dx=e.clientX-aimTouch.x;if(Math.abs(dx)>4){aimTouch.moved=true;state.inner=aimTouch.inner+dx*.014;state.turboReady=distance(launchAngle+state.inner,turboAngle())<.24}});canvas.addEventListener("pointerup",e=>{if(!aimTouch)return;const moved=aimTouch.moved;aimTouch=null;if(!moved)fire()});canvas.addEventListener("pointercancel",()=>{aimTouch=null});addEventListener("keydown",e=>{if(e.code==="Space"||e.code==="Enter"){e.preventDefault();fire()}if(e.code==="ArrowLeft")state.inner-=.16;if(e.code==="ArrowRight")state.inner+=.16});home();
})();
